version: '3.8' 
services: 
  app: 
    build: . 
    ports: 
      - "8080:8080" 
    volumes: 
      - .:/app 
    depends_on: 
      - db 
    network_mode: "host"
    environment: 
      - DB_HOST=127.0.0.1
      - DB_USER=root 
      - DB_PASS=password 
      - DB_NAME=inventory_kantor 
 
  db: 
    image: mysql:5.7 
    restart: always
    network_mode: "host"
    environment: 
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: inventory_kantor