version: "3.9"
services:
  db-invent:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: inventory_kantor
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db-invent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inventory-network


  backend-invent:
    build: .
    depends_on:
      - db-invent
      
    environment:
      DB_HOST: db-invent
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: secret123
      DB_NAME: inventory_kantor
    ports:
      - "8080:8081"
    networks:
      - inventory-network


  nginx-invent:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Inventaris/browser:/usr/share/nginx/html
    networks:
      - inventory-network

networks:
  inventory-network:
    external: true

volumes:
  dbdata:
