version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8081"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=inventory_kantor
    networks:
      - inventory-network

  nginx:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Inventaris/browser:/usr/share/nginx/html
    networks:
      - inventory-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: inventory_kantor
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inventory-network

networks:
  inventory-network:
    external: true

volumes:
  db-data:
    driver: local
